# Default configuration for the evaluation environment
# Not intended to be edited by users. 

: "${BASE_DIR:?BASE_DIR is not set.}"

# Paths of tx tools
ATS_BIN="${BASE_DIR}/../example/ats_frame_generator"
BUSYLOOPETF_BIN="${BASE_DIR}/deps/etfloop/etfloop"

# Paths of calculation scripts
CALCSTATS_BURST="${BASE_DIR}/deps/calc_print_interval.sh"
CALCSTATS_RATE="${BASE_DIR}/deps/calc_interval_rate.sh"
CALCSTATS_OVERLAP="${BASE_DIR}/deps/calc_interval_rate_overlap.sh"
CALCSTATS_INDEP="${BASE_DIR}/deps/calc_interval_rate_indep.sh"
CALCSTATS_LATENCY="${BASE_DIR}/deps/calc_latency.sh"
CALCLATENCY_PY="${BASE_DIR}/deps/_calc_latency.py"
CALCINTERVAL_PY="${BASE_DIR}/deps/_calc_interval_stats.py"
CALCSTATS_SINGLE="${BASE_DIR}/deps/calc_interval.sh"

# Constants
readonly NS_IN_SEC=1000000000
readonly -a ETH_PAYLOAD_SIZES=(46 100 300 500 700 900 1100 1300 1500)
readonly -a UDP_PAYLOAD_SIZES=(18 72 272 472 672 872 1072 1272 1472)

# Paths of clock sync files
PHC2SYS_BIN="${PHC2SYS_BIN:-phc2sys}"
TS2PHC_BIN="${TS2PHC_BIN:-ts2phc}"
TS2PHC_CONFIG="${BASE_DIR}/configs/ts2phc-tsn"
TS2PHC_CONFIG_TEMPLATE="${BASE_DIR}/configs/ts2phc-tsn-template"

# Paths of other configuration files
GRUBFILE=/etc/default/grub
IRQBALANCEFILE=/etc/default/irqbalance
SCALINGGOVERNORFILE=/sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
ISOLATEDCPUSFILE=/sys/devices/system/cpu/isolated