# User-specific configuration required for the evaluation scripts.
# This is an example configuration file. Users should create their own 
# configuration file based on this template and set the necessary variables 
# according to their environment.

# isolcpus setting 
# The value is used to check if the isolcpus setting is correctly applied.
TARGET_ISOLCPUS_LIST="0-4"

# tx configuration
TX_IF=enp1s0
TX_IF_MAC=aa:bb:cc:dd:ee:ff
TX_NETNS_NAME=txnetns
TX_IP=10.0.200.11
TX_SUBNET=24

# rx configuration
RX_IF=enp2s0
RX_IF_MAC=11:22:33:44:55:66
RX_NETNS_NAME=rxnetns
RX_IP=10.0.200.12
RX_SUBNET=24

# Paths of linuxptp tools
#PHC2SYS_BIN=
#TS2PHC_BIN=
